#ifndef _STATUS_H_
#define _STATUS_H_

typedef enum {
  H_SUCCESS,
  H_FAILED_TO_LOAD_ADDRESS,
  H_SERVER_FAILED_TO_START,
  H_CLIENT_FAILED_TO_CONNECT,
  H_FAILED_TO_SEND,
  H_FAILED_TO_RECV
} H_Status;

#endif // !_STATUS_H_
